---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.trendyol.com
  resources:
  - trendyolapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.trendyol.com
  resources:
  - trendyolapplications/finalizers
  verbs:
  - update
- apiGroups:
  - apps.trendyol.com
  resources:
  - trendyolapplications/status
  verbs:
  - get
  - patch
  - update
