apiVersion: apps.trendyol.com/v1
kind: TrendyolApplication
metadata:
  name: trendyol-invalid
spec:
  namespace: default
  image: busybox
  pullSecret: ""
  command: ["/bin/sh"]
  arguments: ["-c", "echo Hello"]
  replicas: 2
  environment:
    FOO: bar

